### PR TITLE
Add testimonials

### PR DESCRIPTION
**Pull request by olafveerman**
This PR add testimonials.

Still to do:

- componentize the testimonials
- handle missing data
- optimize the photos

Over to you @danielfdsilva

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@olafveerman back to you.
Includes the dynamic testimonials and sponsors.

TODO:
- [ ] Add missing images to testimonials
- [ ] Add sponsor names to json file (in content folder)
- [ ] Check quote length

**Comment by olafveerman** [comment]
@danielfdsilva Can you commit `sponsors.json`? You'll have to use `-f`, since JSON files are ignored.

**Comment by olafveerman** [comment]
@danielfdsilva I think we can merge this in. I will open a ticket with pending items on the testimonials.

**Comment by olafveerman** [comment]
@danielfdsilva We can ignore the build failure. Travis is using a cached version of the design system, which is outdated and misses some classes.

**Pull request merged**
