### PR TITLE
Update/517 param filter

### LINKED ISSUE #517: Update Parameter filter emphasizing OpenAQ core parameters
## Goal
We would like to highlight the the original 7 OpenAQ pollutants in the pollutants filters on the Locations and Datasets Hubs by listing them first because those filters will return the most results.

## Details
The 7 original pollutants are:
BC, CO, NO₂, O₃, SO₂, PM2.5, PM10

New pollutants that have been added are:
BC count, CH₄ conc, CO mass, CO₂ conc, NO conc, NO₂ mass, NOx mass, O₃ mass, PM1 mass, SO₂ mass, UFP num, PM0.3 count, PM0.5 count, PM1 count, PM2.5 count, PM5 count, PM10 count, VOC, NOx conc

## Wireframes
Shown below in Tânia's comment.  The [bottommost comment](https://github.com/openaq/openaq.org/issues/517#issuecomment-758550472) is the wireframe to follow.

## Tasks
- [ ] Reorder the parameters
- [ ] Add the 'Core Parameters' and 'Additional Parameters' labels and the associated hover text

## Notes
Someone could start working on this with a hardcoded parameter list, but there is a larger discussion going on about if/how we should note the core OpenAQ parameters.  The results of that discussion will be posted here when the path forward is decided.

### PR DESCRIPTION
**Pull request by jvntf**
closes #517

### CODE REVIEW

**Review by rwegener2 — CHANGES_REQUESTED** [review]
This looks nice and works super well.

#### Two small changes on the "Additional" hover text:
1. Add a period to the end (... _sufficient results._)
2. Change the word "pollutants" to "parameters"
3. Start the sentence with Additional parameters (**Additional parameters** are less common than core parameters_ ...)

You copied the text fine from the ticket I'm just looking at it now and considering these couple things.

#### Slightly bigger but hopefully still not too big change:
* Now that I'm playing with it I think it is a little awkward to have a hover text on just the "Additional" text.  Can we add hover text to the "Core" parameters?  It can say:
> Core parameters are widely available across the OpenAQ platform.

**Comment by jvntf** [comment]
@rwegener2 both changes addressed

**Review by AliceR — APPROVED** [review]
🎉  looks good!

**Review by rwegener2 — APPROVED** [review]
looks niiiiice

**Pull request merged**
