### PR TITLE
Donwload modal

### PR DESCRIPTION
**Pull request by danielfdsilva**
This PR re-implements the Download modal for locations.

- Migrate download modal code to functional components
- Show the parameters with their `displayName` and group them by core/non core
- Ensure Download buttons open the modal (done for locations and country single and hub pages)
- Location fields pre-selected depending on context.

image

### Questions
The modal header displays a message about data availability. Is this still correct?
The `Realtime -> https://openaq-fetches.s3.amazonaws.com/index.html` links to something that doesn't work.
The `daily -> http://openaq-data.s3.amazonaws.com/index.html` looks very outdated.

Everything should be connected and once the api in in place it should work (or minimal changes are required)

### Blockers

The download is not implemented for the datasets, because they're a different entity entirely.
A location has a country/city/location hierarchy (Most actually, some are under "No listed city"). The datasets seem to only have a country, and by looking at the response, the `countries` property is an array. Is it correct to assume a dataset can have multiple countries? Can a dataset not have a country at all?

Besides the above, the endpoint to get a list of datasets is different and the current modal structure can't be used.
A possible option is to add a radio button to the modal where you select what you want to download data for (dataset or location), and change the fields based off of that.

Two options moving forward:
- Ensure the modal works with locations and mark the datasets as coming soon
- Implement the option above

### CODE REVIEW

**Comment by danielfdsilva** [comment]
Added a commit to temporarily disable the data download

image

**Comment by rwegener2** [comment]
closes #562

**Comment by rwegener2** [comment]
@danielfdsilva The measurements endpoint should now properly allow the user to download a csv

### Example & Details
https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/measurements?format=csv
It should be able to be filtered by location.  For the datasets page David recommended using the same endpoint but filtering by the list of locations.  Since a dataset is just a list of locations filtering by a dataset should just mean filtering by all of the locations associated with that datasets.  If this doesn't make sense feel free to ping.

**Comment by danielfdsilva** [comment]
Datasets added as download option.
image

Still left to confirm the header text.

**Comment by rwegener2** [comment]
This looks fantastic.

I say replace the header text with:
> Customize the data you want to download, now including [low cost sensor data](link to blog post). For greater customization, use the [API](http://docs.openaq.org). [Realtime](https://openaq-fetches.s3.amazonaws.com/index.html) archives of all 841,689,793 measurements are also available. 
[Share your feedback](https://docs.google.com/forms/d/1s5GYME3He-EDed-jgg11Ry3zmvTZkPK5xSnQUWwu0Gk/edit) on the low cost sensor pilot so we can continue to improve the platform!

And then merge it!

**Review by rwegener2 — APPROVED** [review]

**Pull request merged**
