### PR TITLE
Improvements to download modal

### PR DESCRIPTION
**Pull request by danielfdsilva**

### CODE REVIEW

**Review by rwegener2 — CHANGES_REQUESTED** [review]
I played with this a bit.  The LCS filter looks nice.  The info button is nice detail.  When I download data it looks like the filter isn't applying, however.  When I go to the modal, enter "United States" and try it twice - once with LCS selected and once with reference selected - the CSVs give me the same results.  It's possible that the API isn't returning correctly, but just post here if that is the case.

The pre-populating of locations that don't have a city works well (two I tried listed below). What seems to be not working not is pre-populating of locations that do have a country listed.  I put some examples below to check into.
### Not working Examples (includes country)
http://localhost:3000/#/location/62446
http://localhost:3000/#/location/62392
### Working Examples (no country)
http://localhost:3000/#/location/67437
http://localhost:3000/#/location/67127

## Summary
* card "[Daniel] add a filter for lcs vs reference data (`sensorType`) for the locations page Data Download modal": GUI is nice, check functionality for filtering
* #625: Complete in the original scope of the ticket.  New filter error with LCS (above) to be investigated
* #626: Original error solved; investigate new error

**Comment by danielfdsilva** [comment]
@rwegener2 Pushed fixes for the pre-selecting bug and rebased from current `develop`

As for the `sensorType`, I see that the URL is being constructed correctly: `https://0jac6b9iac.execute-api.us-east-1.amazonaws.com/v2/measurements?format=csv&limit=66536&country=AD&sensorType[0]=low-cost%20sensor`. However, checking the docs I see that the `sensorType` filter is only available for `/locations`. This will need to be included in the `/measurements` as well. cc @bitner

**Comment by rwegener2** [comment]
Thanks so much @danielfdsilva.  The fixes work really well to me.

I've pinged David about the API request.  So you know we have switched our API addresses to be located on OpenAQ's AWS account.  The new staging url is `https://b4qc1cqcm2.execute-api.us-east-1.amazonaws.com/`.  This URL does seem to have that sensorType filter but I think there is still a bug in it so I've still reached out to David to get that resolved.

**Comment by danielfdsilva** [comment]
@rwegener2 the documentation for `/measurements` lists that `sensorType` as string, but for `/location` is an array.
Given that there are only 2 options, an array is not really useful, but I'd say that the endpoints should have the same api.

I can update this and only include this filter when only 1 option is selected, but ensuring a consistent api could make more sense. Let me know.

**Comment by rwegener2** [comment]
Let's go with the string, as it is on measurements right now.  Standardizing between locations and measurements is a good idea; I'll add that to the list of backend requests for Bitner.

I was hoping to show this to the partner at the top of the hour (11am EST) so if there is time to merge by then that would be great.

**Review by rwegener2 — APPROVED** [review]
🎉 looks and works great

**Pull request merged**
