### PR TITLE
Add news banner

### PR DESCRIPTION
**Pull request by danielfdsilva**
Implemented as outlined in #537

### CODE REVIEW

**Review by rwegener2 — APPROVED** [review]
From a functionality perspective this looks fantastic.

We don't have a blog link from OpenAQ yet.  Should we just merge this after code review and add that link later this week when they will have that published?

**Comment by rwegener2** [comment]
Sorry for the scatterbrained comments, feedback is all over the place.

I found this additional request about the banner:
* center the text
* "call out the links in separate and clear buttons"

That second bullet leaves a bit up to interpretation.  Maybe also underlining them or something to show that they are hyperlinks?  I think the hope might be that we also add the oval box around that text, but I think then we probably want to change the color or styling of the "New" text so that then doesn't appear to also be a link.

**Review by rwegener2 — CHANGES_REQUESTED** [review]
Sorry for the scatterbrained comments, feedback is all over the place.

I found this additional request about the banner:
* center the text
* "call out the links in separate and clear buttons"

That second bullet leaves a bit up to interpretation.  Maybe also underlining them or something to show that they are hyperlinks?  I think the hope might be that we also add the oval box around that text, but I think then we probably want to change the color or styling of the "New" text so that then doesn't appear to also be a link.

**Comment by danielfdsilva** [comment]
@rwegener2 Banner restyled to match new design

**Review by rwegener2 — APPROVED** [review]
Looks great

**Pull request merged**
