### PR TITLE
More map features

### PR DESCRIPTION
**Pull request by AliceR**
Contributing to #472 :
- Limit parameters on world map to hardcoded list in map-settings: not a fan of this approach, but in the same time not sure what a better alternative could be? Since there is the idea of "original" parameters vs. those measured by recently added sources, we need a way to specify which parameters we want to be able to select from the dropdown in the legend. Bonus: one more component without redux.

- Filter map locations by country on country page: using the property `country` provided with the vector tiles

### CODE REVIEW

**Review by jvntf — COMMENTED** [review]
Looks good! I don't know all the details of the 'original' parameters conversation, but perhaps we can just include a flag in the list returned by parameters endpoint ('tileable' or something like that). ParameterConversion factor could also be included.

**Comment by jvntf** [comment]
also latest features have been getting merged to `testing`, perhaps this PR should use that as base?

**Comment by jvntf** [comment]
also looks like this is branched from develop, but just a heads up that latest features have been getting merged to `testing` so might be good to merge that and use it as base.

**Comment by rwegener2** [comment]
This looks nice.  The color scales are operating much more smoothly.  I noticed that some of the units are getting conflated.  For example with CO the stations in the US measuring ppm show up blue while the stations in Europe measuring in ug/m^3 show read because their values are in the hundreds.  On (I believe) the staging API there is a new setup for parameters where the ppm measurements should belong to a parameter `CO conc` and the ug/m^3 belong to a parameter `CO mass`.  The values that should be shown on the OpenAQ map will be the ones labeled "conc" (Ex. BC conc, CO conc, NO2 conc, etc.).  As a general rule we are also denoting parameters by their `displayName`.  I would think that if you merged to testing and used the staging API that you could iron out anything related to that change in parameters (which hopefully isn't too much 🤞 )

One other note about on Countries page:
Something seems a little off with the "locations" number listed on the countries cards.  For some countries, such as Costa Rica (http://localhost:3000/#/countries/CR) locations is 1 but I see no stations.  For others (Germany http://localhost:3000/#/countries/DE or Canada http://localhost:3000/#/countries/CA) the number locations listed is far fewer than the number of points on the map.  What is the source of the "locations" number being displayed on the countries cards right now?
We can fix this in a different PR but I just thought I'd ask the question here since I'm noticing it.

**Comment by AliceR** [comment]
Thanks @jvntf & @rwegener2 , good to hear the parameters are sorted out and provided api side. Sorry that I missed that! I'll rebase onto `testing` and clean up my code 👍 

About the location count, @rwegener2 could you try to scroll down on the country page and see if more locations come up? On small screens it looks like the first section fills the page completely, but there might be more sections. Might be worth a "visual update" along with #513  ?

**Comment by rwegener2** [comment]
@AliceR I added [a card](https://github.com/openaq/openaq.org/projects/1#card-52436897) for the # of locations investigation.  So that issue is now separate from this PR.  It doesn't need to be prioritized.

**Review by jvntf — APPROVED** [review]

**Pull request merged**
