### PR TITLE
Update/point colors

### PR DESCRIPTION
**Pull request by DylanMoriarty**
Makes a new color scale for the point & legend features, satisfying #139. 

Any of @olafveerman @ascalamogna @jflasher for review.

### CODE REVIEW

**Comment by ascalamogna** [comment]
@DylanMoriarty did you update the point size too in this PR? I don't see anything in the commits?

**Comment by DylanMoriarty** [comment]
@ascalamogna nope. I can kick up a slight increase if you think it's still necessary with the color change.

**Comment by ascalamogna** [comment]
@DylanMoriarty Let's give it a slight increase to see how people respond since it's being requested. Unless you think it looks crazy?

**Comment by DylanMoriarty** [comment]
screenshot 2016-11-11 09 41 41

It gets a busier in dense area's, and that masks a few of the smaller points, but that was an issue anyway because the points aren't opaque. The color is indeed clearer, so I think it's better.

For comparison:
screenshot 2016-11-11 10 27 00

**Comment by danielfdsilva** [comment]
@RocketD0g are you ok with the new color scheme?

**Comment by olafveerman** [comment]
@danielfdsilva I think this is good to go. See: https://github.com/openaq/openaq.org/issues/139#issuecomment-258581660

**Pull request merged**
